const titleTyped = new Typed(".title-typed", {
  strings: [
    "I love you",
    "Je t'aime",
    "Vos amo",
    "Quérote",
    "愛している",
    "Eu te amo",
    "Ti amo",
    "愛你",
    "Dich lieben",
    "Amo te",
    "Caru chi",
    "T'estimo",
    "люблю вас",
    "Te iubesc",
    "دوستت دارم",
    "σ'αγαπώ",
    "당신을 사랑합니다",
    "أنا أحبك",
    "Alofa atu",
    "אוהב אותך",
    "Elsker dig",
    "Gràdh ort",
    "чамдаа хайртай",
    "kukuda",
    "Seni seviyorum",
    "Inħobbok",
  ],
  typeSpeed: 80,
  backSpeed: 55,
  startDelay: 300,
  backDelay: 500,
  cursorChar: "█",
  loop: true,
});
